public enum HyperTrackError: String {
    case gpsSignalLost = "gpsSignalLost"
    case locationMocked = "locationMocked"
    case locationPermissionsDenied = "locationPermissionsDenied"
    case locationPermissionsInsufficientForBackground = "locationPermissionsInsufficientForBackground"
    case locationPermissionsNotDetermined = "locationPermissionsNotDetermined"
    case locationPermissionsReducedAccuracy = "locationPermissionsReducedAccuracy"
    case locationPermissionsProvisional = "locationPermissionsProvisional"
    case locationPermissionsRestricted = "locationPermissionsRestricted"
    case locationServicesDisabled = "locationServicesDisabled"
    case locationServicesUnavailable = "locationServicesUnavailable"
    case motionActivityPermissionsNotDetermined = "motionActivityPermissionsNotDetermined"
    case motionActivityPermissionsDenied = "motionActivityPermissionsDenied"
    case motionActivityServicesDisabled = "motionActivityServicesDisabled"
    case motionActivityPermissionsRestricted = "motionActivityPermissionsRestricted"
    case networkConnectionUnavailable = "networkConnectionUnavailable"
    case invalidPublishableKey = "invalidPublishableKey"
    case blockedFromRunning = "blockedFromRunning"
}
