enum TrackingError {
  gpsSignalLost,
  locationMocked,
  locationPermissionsDenied,
  locationPermissionsInsufficientForBackground,
  locationPermissionsNotDetermined,
  locationPermissionsReducedAccuracy,
  locationPermissionsProvisional,
  locationPermissionsRestricted,
  locationServicesDisabled,
  locationServicesUnavailable,
  motionActivityPermissionsNotDetermined,
  motionActivityPermissionsDenied,
  motionActivityServicesDisabled,
  notRunning,
  starting,
  invalidPublishableKey,
  blockedFromRunning
}
